### ISSUE TITLE
The subscription on this account must be upgraded to use the Query API.

### ISSUE THREAD

**Issue by pjwickman** [fulcrumapp/fulcrum-query-utility#5]
Installed the code, login and every Organization I switch to produces this error

`{"error":{"code":1007,"info":"The subscription on this account must be upgraded to use the Query API. To do so, please contact the account owner."}}`

**Comment by oeon** [comment]
Hi @pjwickman 👋, I believe this has been enabled for you now. Feel free to reach out to us if it is not enabled for the specific Organization you're looking to use it on - and we'll make it happen right away. Apologies for the delay response here...we seem to have missed this one. Regards, Joe
