### ISSUE TITLE
Disclaimer after login

### ISSUE THREAD

**Issue by AHelms** [fulcrumapp/fulcrum-query-utility#7]
Since there is the ability to delete data in the Fulcrum database through the FQU we should probably have a disclaimer that needs to be confirmed right after login. Note, there is a disclaimer when attempting to delete data already.

The disclaimer should note that the user is using this tool at the own risk and that FQU is not officially supported.

**Comment by rylincoln** [comment]
How about something like this?  @AHelms  https://cl.ly/19ac9e73cb12

**Comment by AHelms** [comment]
That looks pretty good!

**Comment by bmcbride** [comment]
@rylincoln @AHelms I like it but can we use `localStorage` or something to only prompt it once?

**Comment by bmcbride** [comment]
Closed by ef14fcec1985d8e5ca32fcff089c22afcd8f1733
